
# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.201.229:3306/myinfo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: aHMxODNAcXEuY29t
    filters: wall,mergeStat


# 多数据源情况的配置
myinfo:
  muti-datasource:
    open: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myinfo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    data-source-name: otherdb

#持久层目录
persist:
    pack: com.personal.info.myInfoSystem.modular.system.entity

###通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的；加入这个配置。监控所有接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

